---
title: "Sediment toxicity analysis"
author: ""
output: 
  html_document:
    code_folding: hide
self_contained: yes
---

```{r, echo = F}
library(knitr)
opts_chunk$set(warning = FALSE, message = FALSE, fig.path = 'figs/', dev.args = list(bg = 'transparent'))
```

```{r setup}
library(tidyverse)
library(GGally)
library(vegan)
library(ggdendro)
library(dendextend)
library(FactoMineR)
library(ggord)

data(dat)
```

```{r pairplot, fig.height = 7, fig.width = 7}
ggpairs(dat[, -1])

dat_frm <- dat %>% 
  data.frame %>% 
  column_to_rownames(var = 'station') %>%  
  filter(amph_surv > 30) %>% 
  # filter(tn < 0.4 & toc < 4 & amph_surv > 30)%>% 
  mutate(
    tn = log10(tn), 
    toc = log10(toc),
    fine = ifelse(is.na(fine), mean(fine, na.rm = TRUE), fine), 
    embr_surv = ifelse(is.na(embr_surv), mean(embr_surv, na.rm = TRUE), embr_surv)
  ) %>% 
  decostand(method = 'standardize')
ggpairs(dat_frm[, -1])
```

```{r}
# cluster with euclidean dissim, ward grouping
dend <- dat_frm %>%  
  vegdist(method = 'euclidean') %>% 
  hclust(method = 'average')

ngrps <- 4
grps <- cutree(dend, k = ngrps)

p1 <- dend %>% 
  as.dendrogram %>% 
  set("branches_k_color", k = ngrps) %>%
  set("labels_colors", k = ngrps) %>%
  set("labels_cex", 0.4)
# circlize_dendrogram(p1) 
plot(p1)
```

```{r fig.height = 4, fig.width = 4}
ppp <- PCA(dat_frm, scale.unit = F, graph = F)
dimdesc(ppp, axes = c(1:3))

mythm <- theme_bw(base_family = 'serif') +
  theme(
  legend.position = 'none', 
  strip.background = element_blank(), 
  plot.margin = margin(0, 2, 0, 2, "pt")
) 

p1 <- ggord(ppp, grp_in = as.character(grps), vec_ext = 3, facet = T, nfac = 4, alpha = 0.8, size = 2, txt = 4, arrow = 0.2) + 
  mythm
p1
p2 <- ggord(ppp, grp_in = as.character(grps), axes = c("2", "3"), vec_ext = 3, facet = T, nfac = 4, alpha = 0.8, size = 2, txt = 4, arrow = 0.2) + 
  mythm
p2
```


